from Graph import *
def CreateGraph_1 ():
 G = Graph()
 AddNode(G, Node("A",1,20))
 AddNode(G, Node("B",8,17))
 AddNode(G, Node("C",15,20))
 AddNode(G, Node("D",18,15))
 AddNode(G, Node("E",2,4))
 AddNode(G, Node("F",6,5))
 AddNode(G, Node("G",12,12))
 AddNode(G, Node("H",10,3))
 AddNode(G, Node("I",19,1))
 AddNode(G, Node("J",13,5))
 AddNode(G, Node("K",3,15))
 AddNode(G, Node("L",4,10))
 AddSegment(G, "AB","A","B")
 AddSegment(G, "AE","A","E")
 AddSegment(G, "AK","A","K")
 AddSegment(G, "BA","B","A")
 AddSegment(G, "BC","B","C")
 AddSegment(G, "BF","B","F")
 AddSegment(G, "BK","B","K")
 AddSegment(G, "BG","B","G")
 AddSegment(G, "CD","C","D")
 AddSegment(G, "CG","C","G")
 AddSegment(G, "DG","D","G")
 AddSegment(G, "DH","D","H")
 AddSegment(G, "DI","D","I")
 AddSegment(G, "EF","E","F")
 AddSegment(G, "FL","F","L")
 AddSegment(G, "GB","G","B")
 AddSegment(G, "GF","G","F")
 AddSegment(G, "GH","G","H")
 AddSegment(G, "ID","I","D")
 AddSegment(G, "IJ","I","J")
 AddSegment(G, "JI","J","I")
 AddSegment(G, "KA","K","A")
 AddSegment(G, "KL","K","L")
 AddSegment(G, "LK","L","K")
 AddSegment(G, "LF","L","F")
 return G
print ("Probando el grafo...")
G = CreateGraph_1 ()
Plot(G)
PlotNode(G, "C")
n = GetClosest(G,15,5)
print (n.name) # La respuesta debe ser J
n = GetClosest(G,8,19)
print (n.name) # La respuesta debe ser B


def CreateGraph_2 ():
    G = Graph()
    AddNode(G, Node("P", 3, 18))
    AddNode(G, Node("Q", 7, 14))
    AddNode(G, Node("R", 14, 19))
    AddNode(G, Node("S", 17, 16))
    AddNode(G, Node("T", 5, 6))
    AddNode(G, Node("U", 9, 8))
    AddNode(G, Node("V", 11, 14))
    AddNode(G, Node("W", 12, 4))
    AddNode(G, Node("X", 18, 2))
    AddNode(G, Node("Y", 15, 6))
    AddNode(G, Node("Z", 4, 13))
    AddNode(G, Node("M", 6, 11))

    AddSegment(G, "PQ", "P", "Q")
    AddSegment(G, "PR", "P", "R")
    AddSegment(G, "PZ", "P", "Z")
    AddSegment(G, "QR", "Q", "R")
    AddSegment(G, "QU", "Q", "U")
    AddSegment(G, "QV", "Q", "V")
    AddSegment(G, "RT", "R", "T")
    AddSegment(G, "RS", "R", "S")
    AddSegment(G, "SV", "S", "V")
    AddSegment(G, "SY", "S", "Y")
    AddSegment(G, "SX", "S", "X")
    AddSegment(G, "TU", "T", "U")
    AddSegment(G, "UW", "U", "W")
    AddSegment(G, "VQ", "V", "Q")
    AddSegment(G, "VU", "V", "U")
    AddSegment(G, "VW", "V", "W")
    AddSegment(G, "XW", "X", "W")
    AddSegment(G, "XY", "X", "Y")
    AddSegment(G, "YZ", "Y", "Z")
    AddSegment(G, "ZM", "Z", "M")
    AddSegment(G, "MZ", "M", "Z")
    AddSegment(G, "MT", "M", "T")
    AddSegment(G, "MU", "M", "U")

    return G

G2 = CreateGraph_2()
Plot(G2)

#Probamos leer del archivo

G3 = ReadGraphFromFile("grafo.txt")
Plot(G3)
PlotNode(G3,"I")